In [31]:
comparison

         JLZE001         x
STATEA
1        4712651   4779736
2         691189    710231
4        6246816   6392017
5        2872684   2915918
6       36637290  37253956
8        4887061   5029196
9        3545837   3574097
10        881278    897934
11        584400    601723
12      18511620  18801310
13       9468815   9687653
15       1333591   1360301
16       1526797   1567582
17      12745359  12830632
18       6417398   6483802
19       3016267   3046355
20       2809329   2853118
21       4285828   4339367
22       4429940   4533372
23       1327665   1328361
24       5696423   5773552
25       6477096   6547629
26       9952687   9883640
27       5241914   5303925
28       2941991   2967297
29       5922314   5988927
30        973739    989415
31       1799125   1826341
32       2633331   2700551
33       1313939   1316470
34       8721577   8791894
35       2013122   2059179
36      19229752  19378102
37       9271178   9535483
38        659858    672591
39      11512431  11536504
40       3675339   3751351
41       3761925   3831074
42      12612705  12702379
44       1056389   1052567
45       4511428   4625364
46        799462    814180
47       6234968   6346105
48      24311891  25145561
49       2657236   2763885
50        624258    625741
51       7841754   8001024
53       6561297   6724540
54       1840802   1852994
55       5637947   5686986
56        545579    563626